name: remember_demos
description: "Demos for the Remember App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  drag_and_drop_lists: ^0.4.2
  flutter_guid: ^0.3.1
  intl: ^0.20.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-VariableFont_wght.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster/Lobster-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-VariableFont_wght.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-VariableFont_wght.ttf
